package br.com.rjconsultores.tests.webmodule.seleniumcore.enums;

public enum AttributeKey {
	ELEMENT_ID, 
	ATTRIBUTE_ID, 
	ATTRIBUTE_VALUE, 
	VIEW_NAME, 
	FIND_COMPONENT_BY,
	VALUE_FIND_COMPONENT_BY,
	COMPONENT_NAME,
	COMPONENT_VALUE,
	CLASS_NAME, 
	SESSSION_ID, 
	WAIT_FOR, 
	VALUE_WAIT_FOR,
	PARENT_ELEMENT, 
	FIND_PARENT_BY, 
	FIND_CHILD_BY, 
	SELECT_IDXVALUE, 
	FIND_SIBLING_BY, 
	VALUE_FIND_SIBLING, 
	SIBLING_VALUE,
	CHILD_VALUE, 
	FIND_ATTRIBUTE_BY;
	
}
